### PR TITLE
Filetype optimization

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by ichizok** [comment]
:+1:  入力の重さが改善されました。

```
vim/src/edit.c で計測 (OS X 10.11.2)
:profile! func neocomplete#handler#_do_auto_complete

time per call
before.0:       0.444599
before.1:       0.310365
after.0:        0.316228
after.1:        0.017979
nocf.0:         0.157572
nocf.1:         0.008034

*.0 初回入力時
*.1 初回以降

nocf: g:context_filetype#filetypes = { 'c': [] } を設定
```

**Comment by Shougo** [comment]
Thanks.  I have fixed the problem.  Try this.

@thinca Please test it.

**Comment by thinca** [comment]
:ok: I'll test.

**Comment by thinca** [comment]
No problem.

**Comment by Shougo** [comment]
Merged.  Thanks!

**Pull request merged**
